### ISSUE TITLE
drop

### ISSUE THREAD

**Issue by Matthew-Mosior** [stefan-hoeck/idris2-array#45]
Are there any plans to add `drop` functionality to either `IArray`s or `MArray`s?

**Comment by stefan-hoeck** [comment]
Depends on the runtime behavior you expect. For O(1) drop behavior we'd need backend support: The ability to permanently move an array's position to a new index. In case of raw C pointers this would be trivial (just increase the pointers) but with the backend specific arrays we are using I'm not sure.

The alternative would be an O(n) approach, where we copy the remainder of an array. Finally, we could do what's being done in idris2-bytestring, where we pair byte vectors with an offset into a larger byte array.

To make a long story short: So far it's not yet there because I'm not sure about how to go about it.

**Comment by Matthew-Mosior** [comment]
I think get support for this added initially, I would think an O(n) runtime implementation would fine, and can always optimize as a clearer idea of how to get to O(1) comes into frame.

I'll open a PR for an O(n) solution for now.
